import { NextResponse } from "next/server";
import { requireStaff } from "@/lib/session";
import { PROJECT_TASKS, PROJECT_UPDATES } from "@/lib/admin-data";
import { getProjects } from "@/lib/repos/agency";
import { formatDate, inr } from "@/lib/utils";

export const dynamic = "force-dynamic";

/**
 * Progress report, downloadable as a self-contained HTML file.
 *
 * HTML rather than PDF on purpose: it opens in any browser, prints to PDF
 * from there, and — unlike the pdf-lib route — renders the rupee sign
 * correctly, since the standard PDF fonts have no ₹ glyph.
 */
export async function GET(_req: Request, { params }: { params: Promise<{ id: string }> }) {
  await requireStaff();

  const { id } = await params;
  const { data: projects } = await getProjects();
  const project = projects.find((p) => p.id === id);
  if (!project) return NextResponse.json({ error: "Project not found" }, { status: 404 });

  const tasks = PROJECT_TASKS[id] ?? PROJECT_TASKS.default;
  const updates = PROJECT_UPDATES[id] ?? PROJECT_UPDATES.default;

  const totalWeight = tasks.reduce((s, t) => s + t.weight, 0);
  const doneWeight = tasks.filter((t) => t.status === "DONE").reduce((s, t) => s + t.weight, 0);
  const progress = totalWeight ? Math.round((doneWeight / totalWeight) * 100) : 0;

  const done = tasks.filter((t) => t.status === "DONE");
  const active = tasks.filter((t) => ["IN_PROGRESS", "REVIEW"].includes(t.status));
  const blocked = tasks.filter((t) => t.status === "BLOCKED");
  const upcoming = tasks.filter((t) => t.status === "TODO");

  const esc = (s: string) =>
    s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

  const list = (items: typeof tasks) =>
    items.length
      ? `<ul>${items.map((t) => `<li><strong>${esc(t.title)}</strong> — ${esc(t.discipline)}, ${esc(t.assignee)}${t.status !== "DONE" ? `, due ${formatDate(t.dueDate)}` : ""}</li>`).join("")}</ul>`
      : `<p class="muted">Nothing in this section.</p>`;

  const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>Progress report — ${esc(project.name)}</title>
<style>
  body { font-family: -apple-system, "Segoe UI", Roboto, sans-serif; color: #121F2F;
         max-width: 760px; margin: 40px auto; padding: 0 24px; line-height: 1.65; }
  h1 { font-size: 26px; margin: 0 0 4px; }
  h2 { font-size: 17px; margin: 34px 0 10px; padding-bottom: 8px; border-bottom: 1px solid #E4E4E4; }
  .muted { color: #5C6874; }
  .bar { height: 10px; background: #ECECEC; border-radius: 999px; overflow: hidden; margin: 10px 0 4px; }
  .bar span { display: block; height: 100%; background: #8BB72C; width: ${progress}%; }
  .grid { display: flex; flex-wrap: wrap; gap: 28px; margin: 20px 0; }
  .grid div { min-width: 120px; }
  .grid dt { font-size: 12px; text-transform: uppercase; letter-spacing: .08em; color: #5C6874; }
  .grid dd { margin: 4px 0 0; font-size: 20px; font-weight: 700; }
  ul { padding-left: 20px; margin: 8px 0; }
  li { margin-bottom: 6px; }
  .blocked { background: #FEF2F2; border-left: 3px solid #DC2626; padding: 12px 16px; border-radius: 6px; }
  footer { margin-top: 44px; padding-top: 16px; border-top: 1px solid #E4E4E4; font-size: 12.5px; color: #5C6874; }
  @media print { body { margin: 0; } }
</style></head>
<body>
  <h1>${esc(project.name)}</h1>
  <p class="muted">${esc(project.client)} · progress as at ${formatDate(new Date().toISOString().slice(0, 10))}</p>

  <div class="bar"><span></span></div>
  <p class="muted">${progress}% complete, weighted by task size.</p>

  <dl class="grid">
    <div><dt>Completed</dt><dd>${done.length}</dd></div>
    <div><dt>In progress</dt><dd>${active.length}</dd></div>
    <div><dt>Blocked</dt><dd>${blocked.length}</dd></div>
    <div><dt>Remaining</dt><dd>${upcoming.length}</dd></div>
    <div><dt>Budget</dt><dd>${inr(project.budget)}</dd></div>
  </dl>

  ${blocked.length ? `<div class="blocked"><strong>Blocked:</strong> ${blocked.map((t) => esc(t.title)).join(", ")}. Work downstream of these is on hold.</div>` : ""}

  <h2>Completed</h2>${list(done)}
  <h2>In progress</h2>${list(active)}
  <h2>Coming up</h2>${list(upcoming)}

  <h2>What has happened</h2>
  ${updates.map((u) => `<p><strong>${formatDate(u.createdAt)} — ${esc(u.title)}</strong><br><span class="muted">${esc(u.body)} (${esc(u.author)})</span></p>`).join("")}

  <footer>
    Generated by BMU.Marketing for ${esc(project.client)}. Percentages are weighted by task size,
    so they reflect work completed rather than tasks ticked.
  </footer>
</body></html>`;

  const filename = `${project.name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-progress.html`;

  return new NextResponse(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Cache-Control": "private, no-store",
    },
  });
}
